using Microsoft.EntityFrameworkCore;

namespace Phalanx.Shared.Data;

/// <summary>
/// Creates tables that were added after the initial EnsureCreated() call.
/// Each statement uses IF NOT EXISTS, so it is safe to run on every startup.
/// Add a new block here whenever a new DbSet is introduced.
/// </summary>
public static class SchemaHelper
{
    public static async Task EnsureLatestSchemaAsync(PhalanxContext db)
    {
        // Non-relational providers (InMemory used in tests) don't support raw SQL
        if (!db.Database.IsRelational()) return;

        // EmailEvents — added in v0.4 for phishing / email detection
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "EmailEvents" (
                "Id"             bigint GENERATED BY DEFAULT AS IDENTITY,
                "EventId"        uuid NOT NULL,
                "Timestamp"      timestamp with time zone NOT NULL,
                "IngestedAt"     timestamp with time zone NOT NULL,
                "Action"         text NOT NULL,
                "Dataset"        text NOT NULL,
                "AgentId"        uuid NOT NULL,
                "Hostname"       text NOT NULL,
                "Sender"         text,
                "Recipient"      text,
                "Subject"        text,
                "AttachmentName" text,
                "AttachmentHash" text,
                "ClientProcess"  text,
                "ChildProcess"   text,
                "IndicatorType"  text,
                "Detail"         text,
                "RawJson"        jsonb NOT NULL,
                CONSTRAINT "PK_EmailEvents" PRIMARY KEY ("Id")
            )
            """);

        await db.Database.ExecuteSqlRawAsync(
            """CREATE INDEX IF NOT EXISTS "IX_EmailEvents_Timestamp" ON "EmailEvents" ("Timestamp")""");
        await db.Database.ExecuteSqlRawAsync(
            """CREATE INDEX IF NOT EXISTS "IX_EmailEvents_AgentId"   ON "EmailEvents" ("AgentId")""");
        await db.Database.ExecuteSqlRawAsync(
            """CREATE INDEX IF NOT EXISTS "IX_EmailEvents_Action"    ON "EmailEvents" ("Action")""");
        await db.Database.ExecuteSqlRawAsync(
            """CREATE INDEX IF NOT EXISTS "IX_EmailEvents_Sender"    ON "EmailEvents" ("Sender")""");
    }
}
